### ISSUE TITLE
Find a suitable place for PhotoDatabaseAvailability strings to live

### ISSUE THREAD

**Issue by markdintrepid** [IntrepidPursuits/code-review-bryanw#11]
These strings should probably not live in their own file, but rather with the class that really defines their purpose. In this case, relating back to #2, if you had a "managed document controller" class that handled posting the notification, these strings would live in that class' implementation file.

https://github.com/weberbry/Top-Regions/blob/master/Top%20Regions/PhotoDatabaseAvailability.h

**Comment by weberbry** [comment]
These strings are notification keys so If I put them in a Managed Document Controller class any class that subscribes to the notification will have to implement the same strings. Putting them in a class seemed to be a easy way to ensure that any subscribing class can use the defined string constants to eliminate any chance of typos and allow for easy changes to the keys. 

Is that overkill?
