### ISSUE TITLE
Move remaining onboarding child VC methods/properties into the protocol

### ISSUE THREAD

**Issue by rosslebeau** [IntrepidPursuits/code-review-bryanw#12]
Yep, that ^

**Comment by weberbry** [comment]
addressed in this branch: https://github.com/IntrepidPursuits/onboarding-ios/tree/bweber/Remove_AIAOnboardingChildViewController

**Comment by rosslebeau** [comment]
I made a comment https://github.com/IntrepidPursuits/onboarding-ios/commit/c903bc1bda6591a8f46115a2c3f6f88c489b3f42#commitcomment-9916342

Everything else is good to go. Let me know about that and then I'll close this issue.

**Comment by weberbry** [comment]
change made in this commit: https://github.com/IntrepidPursuits/onboarding-ios/commit/8958278c6bc3941d31ffb42ffc10b3a6dbba3be8

**Comment by rosslebeau** [comment]
Added one comment there :x

**Comment by weberbry** [comment]
change made in this commit: https://github.com/IntrepidPursuits/onboarding-ios/commit/5a071ff7755b1d10fc327777a0134589240470c3
