### ISSUE TITLE
More readable and efficient flow

### ISSUE THREAD

**Issue by rosslebeau** [IntrepidPursuits/code-review-bryanw#14]
https://github.com/IntrepidPursuits/onboarding-ios/blob/34a30b1b06d4aced7823afd41d4bb26f833ebb1f/Onboarding-iOS/UI/Navigation/AIAOnboardingFlowViewController.m#L62

Instead of making a call to `firstObject`, casting it inline for a check, and then immediately making a variable and calling `firstObject` again, I think it would be more readable to do this:

```
AIACheckpoint *firstCheckpoint = self.checkpoints.firstObject;
if (!firstCheckpoint.dateVisited) {
...
```

This also saves an unnecessary second call to `firstObject`...not really important here, but an added benefit that might be useful to think about in other circumstances.

**Comment by weberbry** [comment]
fixed

**Comment by weberbry** [comment]
https://github.com/IntrepidPursuits/onboarding-ios/tree/bweber/Edits-From-Code_Review-2-23
