### ISSUE TITLE
ViewDidLayoutSubviews question

### ISSUE THREAD

**Issue by rosslebeau** [IntrepidPursuits/code-review-bryanw#15]
Why is this code checking if this VC exists every time `viewDidLayoutSubviews` is called?

https://github.com/IntrepidPursuits/onboarding-ios/blob/34a30b1b06d4aced7823afd41d4bb26f833ebb1f/Onboarding-iOS/UI/Navigation/AIAOnboardingFlowViewController.m#L88

**Comment by weberbry** [comment]
This was code Logan and I worked on when we ran into some autolayout issues. The conditional on the VC is used as a flag to make sure the two methods are only called once, even though they are in the viewDidLayoutSubviews method. For some reason if the methods inside the conditional were called from viewWillAppear, the necessary autolayout had not occurred yet. Even if I forced the autolayout with layoutIfNeeded, the constraints just didn't get applied correctly. 

This conditional was our solution.

**Comment by rosslebeau** [comment]
Cool, I think there is a more "correct" way to do this, but it's not really terrible. Maybe we can find another solution and chalk it up as something to learn for next time...even if that lesson end up being "there isn't a better way" haha
