### ISSUE TITLE
Weird comparison

### ISSUE THREAD

**Issue by rosslebeau** [IntrepidPursuits/code-review-bryanw#19]
https://github.com/IntrepidPursuits/onboarding-ios/blob/34a30b1b06d4aced7823afd41d4bb26f833ebb1f/Onboarding-iOS/UI/Navigation/AIAOnboardingFlowViewController.m#L228

The semantics `NOT greater than or equal to one` is more complex, less intuitive, and longer than just saying `less than one`.

**Comment by weberbry** [comment]
fixed

**Comment by weberbry** [comment]
https://github.com/IntrepidPursuits/onboarding-ios/tree/bweber/Edits-From-Code_Review-2-23
