### ISSUE TITLE
Use @class instead of #import whenever possible in header files

### ISSUE THREAD

**Issue by markdintrepid** [IntrepidPursuits/code-review-bryanw#6]
Avoid creating circular references by using the `@class` keyword instead of `#import` in header files.

Ex. https://github.com/weberbry/Top-Regions/blob/master/Top%20Regions/RegionPhotosViewController.h#L10

Replace `#import "Region.h"` with `@class Region;` and move the `#import` statement to the implementation file.

Typically I separate my block of `#import` statements and `@class` statements with a single line of whitespace.

**Comment by weberbry** [comment]
Can we talk about this issue tomorrow. I have a general understanding of the @class notation but not exactly sure when its best used.
